@api = http://localhost:5000/api/products

### Obtener lista de productos
GET {{api}}

### Crear un Producto Nuevo
POST {{api}}
Content-Type: application/json

{
    "name":"monitor",
    "description": "monitor HP",
    "quantity": 15
}

### Obtener Producto por ID
GET {{api}}/6

### Borrar producto por ID
DELETE {{api}}/2

### Obtener el numero de Productos
GET {{api}}/count

### Actualizar un Producto por ID
PUT {{api}}/7
Content-Type: application/json

{
    "name":"Laptop",
    "description": "Laptop Gamer ASUS ROG",
    "quantity": 20
}